### ISSUE TITLE
Do not throw exceptions for unopened closing brackets in lenient mode

### ISSUE THREAD

**Issue by raxbg** [sabberworm/PHP-CSS-Parser#129]
For example this will throw an exception:
```CSS
}.blue{
    background: #00F;
}
```

I think it's okay to ignore it in lenient mode.
