### ISSUE TITLE
Bug in parsing CSS vars

### ISSUE THREAD

**Issue by EvanHerman** [sabberworm/PHP-CSS-Parser#186]
Currently working on a project that uses PHP-CSS-Parser. We've defined some CSS vars in the following manner:
```css
:root {
   --theme-header--bg: 236,47%,46%;
}
```

And then using them throughout our CSS in the following way:
```css
.header__navigation {
   background-color: hsl(var(--theme-header--bg));
}
```

However, when `:root { --theme-header--bg:236,47%,46%; }` is run through `PHP-CSS-Parser` it is stripped and the our CSS declarations where we are using the `--theme-header--bg` var is being dropped.

Original discussion: https://wordpress.org/support/topic/css-hsl-stripped-not-working/

**Comment by westonruter** [comment]
It's actually the `hsl(var(--theme-header--bg))` which is getting dropped.

So given:

```css
:root {
    --theme-header--bg: 236,47%,46%;
}
.header__navigation {
    color: black;
    background-color: hsl(var(--theme-header--bg));
    border: solid 1px red;
}
```

The PHP-CSS-Parser is only able to parse this as: 

```css
:root {
    --theme-header--bg:236,47%,46%; 
}
.header__navigation {
    color:black;
    border:solid 1px red; 
}
```

Notice how `background-color: hsl(var(--theme-header--bg))` is dropped.

A workaround is to move the `hsa()` function to the variable, like so:

```css
:root {
    --theme-header--bg: hsl(236,47%,46%);
}
.header__navigation {
    color: black;
    background-color: var(--theme-header--bg);
    border: solid 1px red;
}
```

But since the browsers work either way, PHP-CSS-Parser should also work.
