### ISSUE TITLE
$block->expandShorthands() adds none-stated values

### ISSUE THREAD

**Issue by Idrinth** [sabberworm/PHP-CSS-Parser#201]
I would have expected it to not add defaults, so that `background: #fff` doesn't suddenly include a statement regarding `background-repeat`

Edit: Code that this happend on:
```css
.x3-login-window .x3-login-window-tr, .x-panel-ghost .x3-login-window-tr {
    background: -moz-linear-gradient(top, #0072a3, #075a79);
    background: -webkit-gradient(linear, 0 0, 0 100%, from(#0072a3), to(#075a79));
    background: linear-gradient(top, #0072a3, #075a79);
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#0072a3', endColorstr='#075a79');
    color: #FFFFFF;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 14px;
    font-style: normal;
    font-weight: bold;
    padding: 3px 3px 0 20px;
    margin: 0 0 5px;
    height: 21px;
}
```

```
array(20) {
  ["filter"]=>
  string(98) "filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#0072a3",endColorstr="#075a79");"
  ["color"]=>
  string(12) "color: #fff;"
  ["font-family"]=>
  string(40) "font-family: Arial,Helvetica,sans-serif;"
  ["font-size"]=>
  string(16) "font-size: 14px;"
  ["font-style"]=>
  string(19) "font-style: normal;"
  ["font-weight"]=>
  string(17) "font-weight: 700;"
  ["height"]=>
  string(13) "height: 21px;"
  ["margin-top"]=>
  string(14) "margin-top: 0;"
  ["margin-right"]=>
  string(16) "margin-right: 0;"
  ["margin-bottom"]=>
  string(19) "margin-bottom: 5px;"
  ["margin-left"]=>
  string(15) "margin-left: 0;"
  ["padding-top"]=>
  string(17) "padding-top: 3px;"
  ["padding-right"]=>
  string(19) "padding-right: 3px;"
  ["padding-bottom"]=>
  string(18) "padding-bottom: 0;"
  ["padding-left"]=>
  string(19) "padding-left: 20px;"
  ["background-color"]=>
  string(30) "background-color: transparent;"
  ["background-image"]=>
  string(23) "background-image: none;"
  ["background-repeat"]=>
  string(26) "background-repeat: repeat;"
  ["background-attachment"]=>
  string(30) "background-attachment: scroll;"
  ["background-position"]=>
  string(27) "background-position: 0% 0%;"
}
```
