### ISSUE TITLE
CSS rgb and rgba functions can't accept custom property

### ISSUE THREAD

**Issue by thomashigginbotham** [sabberworm/PHP-CSS-Parser#257]
The following CSS results in the parser stripping the value.

```css
:root {
  --my-color: 255, 0, 0;
}

body {
  color: rgb(var(--my-color));
}
```

It seems that the parser thinks the value is invalid since `rgb` expects three arguments and is only receiving one. However, the CSS works correctly in every major browser.

The reason I am using this syntax is because I'm passing the `--my-color` variable to various `rgba` functions throughout the style sheet, and while the color might change, the alpha value of each `rgba` function is defined separately. I.e., I can't set `--my-color` to `rgba(255, 0, 0, .5)` as I'd require hundreds of variables for each opacity.

**Comment by thomashigginbotham** [comment]
Actually, it appears that any custom property passed as an argument to `rgb` or `rgba` results in the value being removed. For example:

```css
body {
  color: rgb(var(--color-red), var(--color-green), var(--color-blue));
}
```

results in `body{}`
