### ISSUE TITLE
Unquoted @charset value causes next rule to be dropped

### ISSUE THREAD

**Issue by JakeQZ** [sabberworm/PHP-CSS-Parser#261]
```css
@charset UTF-8;
h1 {
  color: green;
}
p {
  color: green;
}
```

The rule for `h1` gets discarded.  (The rule for `p` is included as expected.)  This _is_ an invalid `@charset` rule (quotes are required for the value), but a reasonable expectation would be for the parser to recover without dropping the next rule.  (Same issue if there's an at-rule following.)

If the `@charset` rule has the required quotes around the value, there is no problem.

```css
@charset "UTF-8";
h1 {
  color: green;
}
p {
  color: green;
}
```
