### ISSUE TITLE
Support for `filter` CSS propery

### ISSUE THREAD

**Issue by milindmore22** [sabberworm/PHP-CSS-Parser#328]
https://developer.mozilla.org/en-US/docs/Web/CSS/filter

```css
/* URL to SVG filter */
filter: url("filters.svg#filter-id");

/* <filter-function> values */
filter: blur(5px);
filter: brightness(0.4);
filter: contrast(200%);
filter: drop-shadow(16px 16px 20px blue);
filter: grayscale(50%);
filter: hue-rotate(90deg);
filter: invert(75%);
filter: opacity(25%);
filter: saturate(30%);
filter: sepia(60%);

/* Multiple filters */
filter: contrast(175%) brightness(3%);

/* Use no filter */
filter: none;

/* Global values */
filter: inherit;
filter: initial;
filter: revert;
filter: unset;
```

**Comment by westonruter** [comment]
This seems to work? In the AMP plugin which uses the CSS parser, I tried adding it to a Custom HTML block with the selector `body` and the above properties and it came through as:

```css
body {
	filter: url("filters.svg#filter-id");
	filter: blur(5px);
	filter: brightness(.4);
	filter: contrast(200%);
	filter: drop-shadow(16px 16px 20px blue);
	filter: grayscale(50%);
	filter: hue-rotate(90deg);
	filter: invert(75%);
	filter: opacity(25%);
	filter: saturate(30%);
	filter: sepia(60%);
	filter: contrast(175%) brightness(3%);
	filter: none;
	filter: inherit;
	filter: initial;
	filter: revert;
	filter: unset;
}
```

@milindmore22 So what isn't working?

**Comment by sabberworm** [comment]
Thanks @westonruter for investigating

**Comment by milindmore22** [comment]
@westonruter

The issue was reported by a user on [support forums](https://wordpress.org/support/topic/amp-img-filter-css/), I think it may be related to #329 the user was using `rgb()` CSS function in the filter.

```css
.drop-shadow {
   filter: drop-shadow(3px 3px 3px rgb(0 0 0 / 0.1));		
}

```
